- id: purge_db_everyday
  alias: "System: Purge DB Everyday"
  initial_state: true
  trigger:
    - platform: time
      at: '01:00:00'
  action:
    - service: recorder.purge
      data:
          keep_days: 5
          repack: true
  mode: single

- alias: "System: Turn OFF switches on Shutdown"
  id: HomeAssistant_shutdown_turn_off_switches
  description: 'Отключение всех устройств при отключении инстанса'
  trigger:
    - platform: homeassistant
      event: shutdown
  condition: []
  action:
    - service: homeassistant.turn_off
      target:
        entity_id:
          - switch.bedroom_air_conditioner_socket
          - switch.bedroom_light_switch
          - switch.bedroom_socket_heating
          - switch.living_room_air_conditioner_socket
        #   - switch.living_room_aquarium_main_lighting
        #   - switch.living_room_aquarium_moonlight
          - switch.living_room_socket_heating
          - switch.living_room_light_switch
          - switch.kitchen_socket_heating
          - light.hallway_rgb_bulb
  mode: single
