homeassistant:
    name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    elevation: 64
    unit_system: metric
    time_zone: Europe/Kiev
    packages: !include_dir_merge_named includes/packages
    customize: !include includes/customize.yaml
    allowlist_external_dirs: "/config/files/"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
    mode: yaml
    resources:
        - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
          type: module
        - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
          type: module
        - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
          type: module
        - url: /hacsfiles/room-card/room-card.js
          type: module
        
# Text to speech
tts:

    - platform: google_translate

    - platform: reversotts
      language: 'Alyona-Russian'
      pitch: "100"
      bitrate: "128k"

# Include External Files
input_boolean: !include includes/input_boolean.yaml
device_tracker: !include includes/device_tracker.yaml

# Include External Folders
automation: !include_dir_merge_list includes/automation
