homeassistant:
    name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    elevation: 64
    unit_system: metric
    time_zone: Europe/Kiev
    country: UA

    packages: !include_dir_merge_named includes/packages
    allowlist_external_dirs: "/config/files/"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
    mode: yaml
    resources:
        - url: /hacsfiles/battery-state-card/battery-state-card.js
          type: module
        - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
          type: module
        - url: /hacsfiles/lovelace-card-mod/card-mod.js
          type: module
        - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
          type: module
        - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
          type: module
        - url: /hacsfiles/room-card/room-card.js
          type: module
        - url: /hacsfiles/stack-in-card/stack-in-card.js
          type: module

# Text to speech
tts:

  - platform: google_translate

  - platform: google_cloud
    key_file: !secret google_cloud_service_keyfile
    voice: uk-UA-Standard-A
    encoding: mp3
    speed: 1.0
    pitch: 0.0
    gain: 0.0
    text_type: ssml

  - platform: reversotts
    language: 'Alyona-Russian'
    pitch: "100"
    bitrate: "128k"

# Include External Folders
automation: !include_dir_merge_list includes/automation

# logger:
#     default: critical
#     logs:
#         custom_components.tapo_control: debug
