title: Home Assistant - сервер

views:
  - !include lovelace/main.yaml
  - !include lovelace/telemetry.yaml
  - !include lovelace/sensors.yaml
  - !include lovelace/electricity.yaml
  - !include lovelace/system.yaml
#   - !include lovelace/packages.yaml
