title: Home Assistant - сервер

views:
   - title: Главная
     icon: mdi:home-assistant

     cards:

       - type: vertical-stack
         cards:     

           - type: entity
             entity: sensor.time_date
             name: Дата/Время
             icon: mdi:calendar-clock

           - type: weather-forecast
             entity: weather.home
             show_forecast: false

           - type: conditional
             conditions:
              - entity: binary_sensor.anyone_home
                state: "on"
             card:
              type: entity-filter
              entities:
                - person.alexus
                - person.inna
                - person.vova
                - person.ivan
              state_filter:
                - home
              show_empty: false
              card:
                type: glance
                show_state: false
                title: Сейчас Дома

       - type: vertical-stack
         cards: 

            - type: grid
              columns: 3
              title: Управление
              cards:
                - type:  conditional
                  conditions: 
                    - entity: input_boolean.heating_status
                      state: 'on'
                  card:
                    type: button
                    tap_action:
                      action: toggle
                    entity: input_boolean.enable_manual_control_heater
                    show_state: false
                    show_name: false
                    hold_action:
                      action: none

                - type: button
                  tap_action:
                    action: toggle
                  entity: input_boolean.enable_manual_control_lights
                  show_state: false
                  show_name: false
                  hold_action:
                    action: none

                - type: button
                  tap_action:
                    action: toggle
                  entity: input_boolean.enable_manual_control_aqua_lights
                  show_state: false
                  show_name: false
                  hold_action:
                    action: none

                # - type: button
                #   tap_action:
                #     action: toggle
                #   entity: input_boolean.enable_manual_control_garlands
                #   show_state: false
                #   show_name: false
                #   hold_action:
                #     action: none


            - type: conditional
              conditions:
                - entity: input_boolean.enable_manual_control_heater
                  state: 'on'
                - entity: input_boolean.heating_status
                  state: 'on'
              card:
                type: grid
                title: Обогреватели
                cards:
                  - type: thermostat
                    entity: climate.living_room_heater
                    name: Гостинная
                  - type: thermostat
                    entity: climate.bedroom_heater
                    name: Спальня
                  - type: thermostat
                    entity: climate.kitchen_heater
                    name: Кухня

            - type: conditional
              conditions:
                - entity: input_boolean.enable_manual_control_lights
                  state: 'on'
              card:
                type: entities
                show_header_toggle: true
                title: Освещение
                icon: mdi:ceiling-light-multiple-outline
                state_color: true
                entities:
                  - entity: switch.living_room_light_switch
                    name: Гостинная
                  - entity: switch.bedroom_light_switch
                    name: Спальня

            - type: conditional
              conditions:
                - entity: input_boolean.enable_manual_control_aqua_lights
                  state: 'on'
              card:
                type: entities
                show_header_toggle: true
                title: Аквариум
                icon: mdi:ceiling-light-multiple-outline
                state_color: true
                entities:
                  - entity: switch.living_room_aquarium_main_lighting
                    name: Основной свет
                  - entity: switch.living_room_aquarium_moonlight
                    name: Лунный свет

            # - type: conditional
            #   conditions:
            #     - entity: input_boolean.enable_manual_control_garlands
            #       state: 'on'
            #   card:
            #     type: entities
            #     show_header_toggle: true
            #     title: Гирлянды
            #     icon: mdi:ceiling-light-multiple-outline
            #     state_color: true
            #     entities:
            #       - entity: switch.living_room_christmas_tree
            #         name: Ёлочная
            #       - entity: switch.living_room_garland_curtain
            #         name: Штора
            #       - entity: switch.living_room_top_garland
            #         name: Верхняя

   - title: Система
     icon: mdi:monitor-dashboard
     cards:

       - type: vertical-stack
         cards:

           - type: entity
             entity: sensor.time_date
             name: Дата/Время
             icon: mdi:calendar-clock

           - type: entities
             show_header_toggle: false
             title: Статус Системы
             entities:
               - entity: sensor.last_boot_custom
                 name: Last boot
               - entity: sensor.online_custom
               - entity: update.home_assistant_core_update
               - entity: sensor.hacs

           - type: entities
             show_header_toggle: false
             title: Статус питания
             entities:
               - entity: sensor.rpi_ac_power_status
               - entity: binary_sensor.ups_battery_low
               - entity: sensor.ups_battery_capacity
               - entity: sensor.ups_battery_voltage

           - type: entities
             show_header_toggle: false
             title: Резервное копирование
             entities:
               - entity: sensor.last_google_backup_train
               - entity: sensor.snapshots_in_google_drive_train
               - entity: sensor.snapshots_in_hassio_train

       - type: vertical-stack
         cards:

           - type: grid
             columns: 2
             title: Системные показатели
             cards:

               - type: gauge
                 name: Загрузка CPU
                 unit: '%'
                 entity: sensor.processor_use
                 severity:
                   green: 0
                   yellow: 60
                   red: 85

               - type: gauge
                 name: Температура CPU
                 unit: '°C'
                 entity: sensor.processor_temperature
                 severity:
                  green: 0
                  yellow: 60
                  red: 85

               - type: gauge
                 name: Загрузка ОЗУ
                 unit: '%'
                 entity: sensor.memory_use_percent
                 severity:
                   green: 0
                   yellow: 60
                   red: 85

               - type: gauge
                 name: Использовано ОЗУ
                 unit: 'МБ'
                 min: 0
                 max: 8192
                 entity: sensor.memory_use
                 severity:
                   green: 0
                   yellow: 6144
                   red: 7168

               - type: gauge
                 name: Диск Заполнен
                 unit: '%'
                 entity: sensor.disk_use_percent
                 severity:
                   green: 0
                   yellow: 60
                   red: 85

               - type: gauge
                 name: Свободное Место
                 unit: 'Гб'
                 entity: sensor.disk_free
                 severity:
                   red: 50
                   yellow: 150
                   green: 250         

       - type: vertical-stack
         title: Статистика БД
         cards:

           - type: entities
             show_header_toggle: false
             entities:
               - entity: sensor.maria_db_size
                 name: Объем БД
                 icon: mdi:database

           - type: history-graph
             entities:
               - entity: sensor.maria_db_size
             name: Maria DB

       - type: vertical-stack
         title: Интернет  Соединение
         cards:
           - type: entity
             entity: sensor.archer_c80_router_external_ip
           - type: sensor
             entity: sensor.speedtest_download
             graph: line
           - type: sensor
             entity: sensor.speedtest_upload
             graph: line

       - type: vertical-stack
         cards:
          - entities:
              - entity: input_boolean.heating_status
              - entity: input_boolean.disable_climate
              - entity: input_boolean.disable_home_away
              - entity: input_boolean.disable_zone_notifications
              - entity: input_boolean.disable_climate_notifications
              - entity: input_boolean.disable_startup_notifications
              - entity: input_boolean.disable_occupancy
            show_header_toggle: false
            title: Отмена Автоматизаций
            icon: mdi:sync-off
            type: entities
            state_color: true

   - title: Сенсоры
     icon: mdi:motion-sensor

     cards:

       - type: vertical-stack
         title: Гостинная
         cards:
            - type: entities
              entities:
                - entity: binary_sensor.living_room_loggia_door_contact
                  name: Дверь на лоджию
                - entity: binary_sensor.living_room_auto_light_off_sensor
                - entity: binary_sensor.living_room_lumi_sensor_motion_occupancy
                  name: Датчик движения
                - entity: sensor.living_room_lumi_sensor_motion_illuminance_lux
                  name: Освещенность
                - entity: sensor.living_room_lumi_weather_humidity
                  name: Влажность
                - entity: sensor.living_room_lumi_weather_pressure
                  name: Давление
                - entity: sensor.living_room_lumi_weather_temperature
                  name: Температура

       - type: vertical-stack
         title: Спальня
         cards:
            - type: entities
              entities:
                - entity: binary_sensor.bedroom_window_left_contact
                  name: Окно, левая створка
                - entity: binary_sensor.bedroom_window_right_contact
                  name: Окно, правая створка
                - entity: binary_sensor.bedroom_auto_light_off_sensor
                - entity: binary_sensor.bedroom_lumi_sensor_motion_occupancy
                  name: Датчик движения
                - entity: sensor.bedroom_lumi_sensor_motion_illuminance_lux
                  name: Освещенность
                - entity: sensor.bedroom_lumi_weather_humidity
                  name: Влажность
                - entity: sensor.bedroom_lumi_weather_pressure
                  name: Давление
                - entity: sensor.bedroom_lumi_weather_temperature
                  name: Температура

       - type: vertical-stack
         title: Кухня
         cards:
            - type: entities
              entities:
                # - entity: binary_sensor.kitchen_auto_light_off_sensor
                # - entity: binary_sensor.kitchen_lumi_sensor_motion_occupancy
                #   name: Датчик движения
                # - entity: sensor.kitchen_lumi_sensor_motion_illuminance_lux
                #   name: Освещенность
                - entity: binary_sensor.kitchen_window_contact
                  name: Окно
                - entity: sensor.kitchen_lumi_weather_humidity
                  name: Влажность
                - entity: sensor.kitchen_lumi_weather_pressure
                  name: Давление
                - entity: sensor.kitchen_lumi_weather_temperature
                  name: Температура
                - entity: binary_sensor.kitchen_smoke_detector_smoke
                  name: Датчик дыма
                - entity: binary_sensor.kitchen_water_leak_sensor_water_leak
                  name: Датчик протечки

       - type: vertical-stack
         title: Ванная
         cards:
            - type: entities
              entities: 
                - entity: sensor.bathroom_lumi_weather_humidity
                  name: Влажность
                - entity: sensor.bathroom_lumi_weather_pressure
                  name: Давление
                - entity: sensor.bathroom_lumi_weather_temperature
                  name: Температура
                - entity: binary_sensor.bathroom_water_leak_under_the_bath_water_leak
                  name: Датчик протечки, под ванной
                - entity: binary_sensor.bathroom_water_leak_under_washing_machine_water_leak
                  name: Датчик протечки, под стиральной машиной

       - type: vertical-stack
         title: Коридор
         cards:
           - type: entities
             entities:
               - entity: binary_sensor.corridor_entrance_door_contact
                 name: Входная дверь

       - type: vertical-stack
         title: Лоджия
         cards:
           - type: entities
             entities:
               - entity: sensor.loggia_tuya_weather_humidity
                 name: Влажность
               - entity: sensor.loggia_tuya_weather_temperature
                 name: Температура
